export const VdashaCardDetails = {
  Rahu: [
    "If Rahu is in the eighth house of the Kundli during birth, it could indicate some sort of mortal danger to the life of the native and appropriate measures are required to counter this effect. This placement of Rahu, however, is extremely beneficial for those who are from the rahu-favoured signs as they will experience a sudden surge in financial aspects. But this increase in wealth could be two sides of the same coin, the other side being that you acquire this wealth by some evil means like theft. You might also suffer from some sort of disease, thus you should take care of your health more than before.",
    "The planet Rahu is in the Capricorn sign of the Kundli. This placement will bring happiness and comfort to the life of the native. Even though things won't go as smoothly as you would like them to go, however, you will experience smooth sailing when it comes to your love and professional life. The placement of Rahu in Capricorn indicates that you will find respect and reverence in society. There is a possibility, however, that things change for worse towards the end of this Dasha period if you are not careful about your life decisions. Health and disease is something for you to be on the lookout for. Rahu in Capricorn further indicates that your happiness can be dependent on the loyalty that your subordinates and your loved ones show to you.",
  ],
  Jupiter: [
    "The planet Jupiter is in the first house of the Kundli. During this Dasha period, you shall attain good health and be contented mentally. With gains in professional life, you would also earn benefits from the lands and properties you own. As the Dasha time moves ahead, you can anticipate the birth of a child in your house. Moreover, you shall also earn renowned fame and prosperity from all edges and ends. With Jupiter in the first house in the Dasha period, you have fewer chances of bumping into misfortunes and bad luck. Therefore, the Dasha shall be favorable for those planning something auspicious in their personal life.",
    "The planet Jupiter is camping with the Gemini sign in the Kundli. This placement hints at some unhappy instances in life. Your unhappiness might derive particularly from your domestic life. Hence it is better that you give attention to it. The placement of Jupiter in Gemini suggests that you might become estranged from your spouse. At some point during the Dasha period, you are quite likely to find yourself in a leading role in some religious activity or event. Jupiter in Gemini further suggests that you will attend church or temple, etc. regularly, and seek solace in your religion.",
  ],
  Saturn: [
    "The planet Saturn is in the seventh house of the Kundli. During this Dasha period, you might have to go through deprivation in wealth because of some extra expenses. All this could eventually lead to unhappiness and stress. As the Dasha time moves ahead, evil thoughts will take a high place in your head. The best way to tackle all of this? Well, that would be keeping yourself busy with hard work. This will not only add to your fortune in the later dasha period but will also help you prevent stress and unhappiness of any kind. All in all, you need to be careful until the Dasha ends",
    "The planet Saturn is camping with the Sagittarius sign in the Kundli. This placement will bring happiness to the native’s life. The native, who has Saturn in this position at birth, is a man of action. The placement of Saturn in Sagittarius indicates that you are a fighter who can succeed even if all odds are stacked against him. Your drive, conviction and commitment to your work will bring you tremendous joy. You will be content with the work that you do. This Dasha period is an extremely happy one for the native. Saturn in Sagittarius further indicates that you will succeed in your enterprises, should you try to build any.",
  ],
  Mercury: [
    "The planet Mercury is in the eighth house of the Kundli. During this Dasha period, things would run positively in your life. You will attain recognition in society, and fame from your righteous deeds will come to you. As the Dasha time moves ahead, you would capably help your relatives in all manners and shall encounter peace in it. Gains from the profession as well as land and properties would be in your bag as well. Not just this, with Mercury in the eighth house in the Dasha period, happiness will find its way to you in terms of wealth and satisfying family life.",
    "The planet Mercury is camping with the Capricorn sign in the Kundli. This placement marks the period of movement for you. The placement of Mercury in Capricorn suggests that there will be continuous travel and many short journeys in this Dasha period as well. There will be numerous travels in your life, primarily by land. During this period, the native may come in contact with people who are his/her inferiors. You will tend to be around people among whom you have authority and who considers you as their superiors. You succumb to flattery. With the help of such associates, you might scheme against your employers and also those who have authority over you. Mercury in Capricorn further suggests that you will spend money recklessly in an endeavour to show off to those who flatter you.",
  ],
  Ketu: [
    "The placement of Ketu in the second house of the Kundli during the birth of the native might tempt them to act like a cynic and use harsh speech. Due to exposure to some hard time, the person could become rough around the edges, and he or she could act a little harsh hearted. The changes could be brought about due to the person’s experience with, sorrow and friction in the family. However, all of this is not worthless as it will help you in the professional world. You will be able to acquire enough wealth from multiple sources. You will also be able to attract the attention of your opposite gender through your personality.",
    "The planet Ketu is in the Cancer sign of the Kundli. During this Dasha, scenarios in your life might sway. Though there are hints of minor casualties in terms of health, but for the most part, you would get happiness in your life from your spouse and children. However, at the end of the dasha period, the planet Ketu may prompt you to acquire some bad habits. This could have an adverse effect on your personal and professional life. Also, you must give up on your habit of procrastination. And if you do, you will be able to make a fortune during this period.",
  ],
  Venus: [
    "The planet Venus is in the eighth house of the Kundli. During this Dasha period, wealth-wise, things would run smoothly in your life. With the gain in business, you can expect happiness and prosperity in your personal life. As the Dasha time passes by, things may take an unexpected turn, and you may get into materialistic tendencies and have ill health. Wounds and injuries may chase you, and fear from fire and weapons could be there too. Moreover, with Venus in the eighth house in the Dasha period, things would get better in the last few months. You would attain respect and gain from ruler-like folks in your life and have occasional happiness.",
    "Venus is camping with the Capricorn sign in the Kundli. With this positioning, the native may encounter happy times but with some ups and downs. Therefore, you may prefer to reside away from your homeland. The same shall prove a successful move in the long run. Also, with the placement of Venus in Capricorn, problems in business and progress would settle without troubles or hurdles. Moreover, you will liquidate as an individual in all means and manners. However, your domestic life may sway between good and bad times, which will eventually turn into good at the end of the Dasha period.",
  ],
  Sun: [
    "The planet Sun is in the seventh house of the Kundli. During this Dasha period, you are likely to face some health issues, specifically near the ear area. Thus it is recommended that you cut your screen time. Also, you might have wrongful tendencies, and you may bear some wickedness from the spouse's side. The dasha period, however, is good if you are into some food-related business. You will have the luck to make good profits in it. Also, with Sun in the seventh house in the Dasha period, there could be cravings regarding dairy products such as ghee, milk, curd, etc.",
    "The Sun is camping with the Sagittarius sign in the Kundli. This placement will bring success in your life, especially in terms of your finances. The native can make huge profits by making some smart investments during this Dasha period. You will find prosperity in your financial ventures. The placement of the Sun in Sagittarius will further bring you success in your career in the form of promotions and increased authority at your job or community. This means you will also have more responsibilities coming your way. The Sun in Sagittarius also indicates that you will live a comfortable life during this Dasha period and experience solace and dignity along will pleasure and happiness. You might also find yourself attending cultural events such as operas and concerts as your taste in culture grows.",
  ],
  Moon: [
    "The planet Moon is in the ninth house of the Kundli. During this Dasha period, you shall seek favourable possibilities mixed with some downsides. You would own a new name and fame in the society. If put in other words, your popularity among your known ones would increase. With that, you will be involved in upstanding deeds, and the same would provide you satisfaction and recognition in the long run. As the Dasha moves on, things will become more gratifying for you. With success in projects and ventures, you would seek a notable hike in your finances. Childbirth and an appeasing time with the family will be there as well. Furthermore, ornamental happiness and other sorts of leisure would knock at your door with the Moon in the ninth house in the Dasha period.",
    "The Moon is camping with the Aquarius sign in the Kundli. This placement suggests that the native will make reckless expenditures. Your tendency to spend luxuriously might bury you in debt which is why you need to be careful to not borrow unless extremely necessary. The placement of the Moon in Aquarius also suggests that you may face difficulties in paying off your debt and may make horrible mistakes in your budget if you are careless. Thus the Moon in Aquarius wants you to rely on multiple sources of income. Don't take shortcuts, as they would be futile.",
  ],
  Mars: [
    "The planet Mars is in the sixth house of the Kundli. During this Dasha period, things are likely to run pretty positively. You shall possess all the fame in the world and would be famous because of your righteous deeds. Also, you would succeed over enemies and be able to influence the same. Finances will get better too. You can even count on this time for savings and investment of your money. However, as the Dasha time passes, scenarios might take a negative turn. You may suffer from minor health problems. And, not just you, your maternal uncles might run into ailments too. With Mars in the sixth house in the Dasha period, things will get better by the end. You shall earn hikes with property and land. With that, purchasing the same too will give you benefits in the long run.       ",
    "The planet Mars is camping with the Scorpio sign in the Kundli. This placement brings much sensuality to the natives. You will crave a relationship in this period is likely will be lucky to find one for yourself. The placement of Mars in Scorpio is good for any kind of agriculture-related business. In this period, you will think about marriage a lot and you might find yourself involved in an affair. However, make sure you don't involve yourself in flings as these would be disastrous for you. The native must also take special care of their parents.",
  ],
};

export const returnDetails = (e) => {
  return VdashaCardDetails[e];
};
export const planatryDetails = {
  Sun: [
    "If Rahu is in the eighth house of the Kundli during birth, it could indicate some sort of mortal danger to the life of the native and appropriate measures are required to counter this effect. This placement of Rahu, however, is extremely beneficial for those who are from the rahu-favoured signs as they will experience a sudden surge in financial aspects. But this increase in wealth could be two sides of the same coin, the other side being that you acquire this wealth by some evil means like theft. You might also suffer from some sort of disease, thus you should take care of your health more than before.",
    "The conjunction also indicates that you may suffer from mental stress because of unnecessary hidden matters or worries. Also, you might face fighting or quarrel issues regarding land and property, vehicles and may lose wealth on professional grounds. Losses regarding administration or government firms may also occur.",
  ],
  Moon: [
    "The planet Moon is in the tenth house of your natal chart with the Aquarius sign. It says that the native will be great in sea or transport professions. So, you will be intelligent, brave, and reluctant about any actions in your professional life. You will gain great respect and social fame in society and be very active in terms of responsibilities.",
    "You will maintain happy relations with your mother, seek help from your siblings, and believe in making happy memories. On the positive side, you will have high-class and nice-natured friends, and on the negative side, you may have many enemies who can cause you mental stress. You might be shameless about earning riches and would be someone with an analytical, money-making, and creative mind. You would travel a lot because of your career but may possess drinking habits on business trips.",
  ],
  Mercury: [
    "The planet Mercury is in the eighth house of the Kundli. During this Dasha period, things would run positively in your life. You will attain recognition in society, and fame from your righteous deeds will come to you. As the Dasha time moves ahead, you would capably help your relatives in all manners and shall encounter peace in it. Gains from the profession as well as land and properties would be in your bag as well. Not just this, with Mercury in the eighth house in the Dasha period, happiness will find its way to you in terms of wealth and satisfying family life.",
    "There are high chances that you might possess wealth with your educational qualifications. Also, you would be someone who would love to travel a lot. You will interact with folks of varying ethnicity. If we see your family relations, you will be fortunate in terms of that. Your bond with your children will be very harmonious, and your siblings will possess a helping nature towards you.",
  ],
  Venus: [
    "The planet Venus is in the ninth house of your natal chart with the Capricorn sign. Venus in this house usually shows favorable results. You will be lucky, destined as well as fortunate in terms of settlements in life. You would do great in attaining the goals of your life. Though you won’t be able to progress in Dharma, but still be able to possess spirituality. You would seek help from your siblings, would be on auspicious terms with your father, and would get lucky in the family.",
    "As for personality, this conjunction will make you clever and gentlemanly. You will be brainy in wealth matters and plan towards life. There are also high chances that you might go short travels to foreign lands. Your possibilities of possessing success in the house of rivals are also high.",
  ],
  Mars: [
    "The planet Mars is in the seventh house of your natal chart with the Scorpio sign. It indicates that the native will face a competitive background. So, there are chances that you might draw strong competitive people towards you. Your spouse will be goal-oriented, self-driven, a bit tomboyish, and will stand by your side like a fighter. Despite all these factors, you may have mixed relations with your spouse. Happiness might sway between you two. Also, there are chances that you might feel weakness in terms of sexual pleasures.",
    "If we talk of professional life, you will possess a zealous personality; will earn great riches if focused on the occupation you choose. But, on the downside, there might be a loss of wealth waiting for you at every step of life. You might spend money to possess royal or kingly life and possess the weak dignity of the family.",
  ],
  Jupiter: [
    "The planet Jupiter is in the second house of your natal chart with the Gemini sign. The native with this conjunction won’t show unfavorable results. You will experience gain and progress in terms of wealth. But despite this fact, you might still face instability in finances. Speaking of family and relations, your family members won’t be supportive regarding you. You will live far away from the family. There might be high chances that you might go through a few unhappiness regarding your father.",
    "Though your tone will be sweet and pleasing, yet you will not have great connections with people around you. In terms of health, this conjunction may not show many positive results. You might face many accidents and go through many small and short-term diseases throughout your life. You may go through many loans and debts, face delays in competition and other works. Thus, work-related issues might always be surrounding you.",
  ],
  Saturn: [
    "The planet Saturn is in the eighth house of your natal chart with the Sagittarius sign. This conjunction usually may not show many favorable results for the native. In terms of professional life, you will face multiple changes in jobs, and hurdles would be waiting for you at every step of life. Unsettlement might be there throughout your life. Fortune might work in favor, and so possibilities are there that you won’t be able to give your all-in in any work you would do.",
    "You may lead a hectic life with a grave of problems. Your family relations might not be positive. You might face unsupportiveness from the whole family, distress with the father, and issues with children. With that, you could face deficiency in possessing fame. But on the brighter side, you will get foreign cooperation and union progress via diligence. You will be of divine power, well-educated, and with manners and stability.",
  ],
  Rahu: [
    "The planet Rahu is in the ninth house of your natal chart with the Capricorn sign. The native possibly will go through mixed results with this conjunction. So, you might go through a massive loss in the house of destiny. On one side, you might be highly religious, while, on the other side, you might make mistakes regarding Dharma.",
    "There are high possibilities that you have foreign travels a lot. The reason for it may be professional or educational. You might not attain a great name or fame but will still manage a consistent image in society. You would be great in research studies, and with hard work, you will achieve astonishing heights. Overall, Rahu will give more positive results than negative ones.",
  ],
  Ketu: [
    "The planet Ketu is in the third house of your natal chart with the Cancer sign. The native with this conjunction has high chances of possessing almost all debilitating effects. Thus, regarding your family, you might face many misunderstandings with your family. You may have to face separation from your siblings, dissatisfaction from your mother, and issues with your spouse. Your personality may not be very pleasing to people, yet, you would be brave, courageous, and diligent. Your life might go into worries, restlessness, and non-Dharmic deeds.",
    "There might be issues regarding finances as well. You may face problems in the course of earning a basic daily wage, but hard work will make it work anyway. You will do energetic deeds but would find it hard to progress in stuff. Overall, this conjunction might lead you to many downfalls all your life.",
  ],
};

export const returnPlanetryDetails = (e) => {
  return planatryDetails[e];
};
